name: Deploy React to Lambda
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookstore-frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      #  Build 
      - run: npm ci
      - run: npm run build
      
      #  Clean up 
      - name: Clean up dev files
        run: |
          rm -rf node_modules
          rm -rf src
          rm -rf public
  	  rm -f server.js

      # specific stable version
      - name: Install Stable Server Deps
        run: npm install express@4.18.2 serverless-http@3.2.0 --save-prod

      # Install Serverless 
      - run: npm install -g serverless@3
      
      # Deploy
      - name: Deploy
        run: serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}